version: "3.7"
services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    sql:
        image: chriszupancic/librarysql:latest
        ports:
            - "1433:1433"